version: '3'

services:

  flask_service:
    container_name: gringotts_flask
    restart: always
    image: flask
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask/app:/var/www/flask/app
      - ./flask/config:/var/www/flask/config
    environment:
        - FLASK_APP=wsgi.py
        - FLASK_DEBUG=1
        - CONFIG_ENV="production"
        - CRYPTO_KEY="aWV0tnyeoDbWPjmAKjwV_Q6dAPTy_wjdVJGf-iwJjfY="

  gui_service:
    container_name: gringotts_ghi
    restart: always
    image: gui
    build:
      context: ./gui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./gui/*:/var/www/gui/*
